server:
  port: 9081
spring:
  application:
    name: eStore Product Microservices
  data:
    mongodb:
      host: localhost
      port: 27017
      database: estore
  profiles:
    active: dev, test, prod
logging:
  file:
    name: d:\logs\eStore-product-v1.log
  logback:
    rollingpolicy:
      max-file-size: 100MB

product:
  currencies:
    - EUR
    - USD
    - FCFA

---
server:
  port: 9085
spring:
  config:
    activate:
      on-profile:
        - prod