server:
  port: 9081
spring:
  application:
    name: eStore Product Microservices
  data:
    mongodb:
      host: localhost
      port: 27017
      database: estore
  profiles:
    active: dev, test, prod
  boot:
    admin:
      client:
        url:
          - http://localhost:8081
logging:
  file:
    name: d:\logs\eStore-product-v1.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    mongo:
      enabled: true
info:
  app:
    name: eStore Product Microservice
    version: 1.0
    decription: CRUD Product Microservice
product:
  currencies:
    - EUR
    - USD
    - FCFA
